// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbh7T34sBO9WWDf7Ug7IUd9AuBIds8aQ',
    appId: '1:34633959954:web:439860499d20db24bce6cb',
    messagingSenderId: '34633959954',
    projectId: 'mobiledev-a715a',
    authDomain: 'mobiledev-a715a.firebaseapp.com',
    databaseURL: 'https://mobiledev-a715a-default-rtdb.firebaseio.com',
    storageBucket: 'mobiledev-a715a.appspot.com',
    measurementId: 'G-JF1YH1PDD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWY2l8-GKZNHNc__H0RmfKfCm4hi215jQ',
    appId: '1:34633959954:android:cb267737a5305323bce6cb',
    messagingSenderId: '34633959954',
    projectId: 'mobiledev-a715a',
    databaseURL: 'https://mobiledev-a715a-default-rtdb.firebaseio.com',
    storageBucket: 'mobiledev-a715a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHzvHWTbuPbf9cOP3oulqTrBbe7gyalQ',
    appId: '1:34633959954:ios:628d5852b6240729bce6cb',
    messagingSenderId: '34633959954',
    projectId: 'mobiledev-a715a',
    databaseURL: 'https://mobiledev-a715a-default-rtdb.firebaseio.com',
    storageBucket: 'mobiledev-a715a.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHzvHWTbuPbf9cOP3oulqTrBbe7gyalQ',
    appId: '1:34633959954:ios:8a89f626ccd1b912bce6cb',
    messagingSenderId: '34633959954',
    projectId: 'mobiledev-a715a',
    databaseURL: 'https://mobiledev-a715a-default-rtdb.firebaseio.com',
    storageBucket: 'mobiledev-a715a.appspot.com',
    iosBundleId: 'com.example.assignment2.RunnerTests',
  );
}
